### ISSUE TITLE
Cannot connect to remote redis

### ISSUE THREAD

**Issue by wajahathpw220** [long2ice/rearq#12]
Traceback (most recent call last):
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/bin/rearq", line 8, in <module>
    sys.exit(main())
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/lib/python3.9/site-packages/rearq/cli.py", line 100, in main
    cli()
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/lib/python3.9/site-packages/rearq/cli.py", line 20, in wrapper
    return loop.run_until_complete(f(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/lib/python3.9/site-packages/rearq/cli.py", line 63, in worker
    await w.run()
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/lib/python3.9/site-packages/rearq/worker.py", line 265, in run
    await self._pre_run()
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/lib/python3.9/site-packages/rearq/worker.py", line 249, in _pre_run
    raise e
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/lib/python3.9/site-packages/rearq/worker.py", line 244, in _pre_run
    await self._redis.xgroup_create(self.queue, self.group_name, mkstream=True)
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/lib/python3.9/site-packages/aioredis/client.py", line 1085, in execute_command
    return await self.parse_response(conn, command_name, **options)
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/lib/python3.9/site-packages/aioredis/client.py", line 1101, in parse_response
    response = await connection.read_response()
  File "/home/wajahath/Desktop/projects/fastApiProject/venv/lib/python3.9/site-packages/aioredis/connection.py", line 919, in read_response
    raise response from None
aioredis.exceptions.ResponseError: unknown command 'XGROUP'

Process finished with exit code 1

I'm trying to connect to a remote redis, (which is accessible through out the redis cli, but not with the rearq, )
But i'm able to connect to local redis of same version

**Comment by long2ice** [comment]
Upgrade redis > 5.0

**Comment by wajahathpw220** [comment]
> Upgrade redis > 5.0

Thanks, that might be  the issue.
